version: '3.6'

services:


  web:
    image: nginx
    container_name: galeno-nginx
    restart: always
    volumes:
      - "./galeno-app:/var/www/html"
      - "./nginx:/etc/nginx/"
    ports:
      - "9322:80"


  php:
    #image: php:7.2-fpm
    container_name: galeno-php
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - "./galeno-app:/var/www/html"

  mariadb:
    image: mariadb
    container_name: galeno-db
    restart: always
    volumes:
      - galeno-db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: galeno
    secrets:
      - db_root_password
    ports:
      - "127.0.0.1:3322:3306"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: galeno-pma
  #   restart: always
  #   environment:
  #     - PMA_HOST=galeno-db
  #   ports:
  #     - "127.0.0.1:9301:80"


secrets:
   db_root_password:
     file: ./secrets/db_root_password


volumes:
  galeno-db-vol:
