version: '3.6'

services:


  web:
    image: nginx
    container_name: medicoffice-nginx
    restart: always
    volumes:
      - "./app:/var/www/html"
      - "./nginx:/etc/nginx/"
    ports:
      - "127.0.0.1:9000:80"


  php:
    image: php:7.2-fpm
    container_name: medicoffice-php
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - "./app:/var/www/html"

  mariadb:
    image: mariadb
    container_name: medicoffice-db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: medicoffice
    secrets:
      - db_root_password
    ports:
      - "127.0.0.1:3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cci-pma
    restart: always
    environment:
      - PMA_HOST=medicoffice-db
    ports:
      - "127.0.0.1:9001:80"


secrets:
   db_root_password:
     file: ./secrets/db_root_password
